{% set name = "smartypants" %}
{% set version = "2.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/leohemsted/{{ name }}.py/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 560ae7485a27c288f5bd63131f5c3c7b8f0745f50e7c3f85f0bbc65d87799d19

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools

  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - smartypants
  commands:
    - pip check

about:
  home: https://github.com/leohemsted/smartypants.py
  license_file: COPYING
  license: BSD-3-Clause
  license_family: BSD
  summary: 'Python with the SmartyPants'
  dev_url: https://github.com/leohemsted/smartypants.py
  doc_url: https://pythonhosted.org/smartypants/

extra:
  recipe-maintainers:
    - pmlandwehr
    - thewchan
